package tawjih.enums;

public enum Specialite {
    SCIENCES_MATH_A,
    SCIENCES_MATH_B,
    SCIENCES_PHYSIQUES,
    SCIENCES_VIE_TERRE,
    SCIENCES_AGRO,
    SCIENCES_ECONOMIQUES,
    GESTION_ACCOUNTING,
    LETTRES_MODERNES,
    LETTRES_CLASSIQUES,
    SCIENCES_HUMAINES,
    ARTS_APPLIQUES
}
